### PR TITLE
Fixed some calculation bugs and improve calculation readability

### LINKED ISSUE #31: Arithmetic bug in Dale Chall readability score
It looks like there is an arithmetic bug in the Dale Chall calculations caused by some interesting code styling mixed with what I believe is a bug in the Ruby parser

Specifically with:
https://github.com/kupolak/textstat/blob/master/lib/textstat.rb#L182-184

The way the Ruby parser works, this is actually assigning only the last line ie `(0.0496 * avg_sentence_length(text))` to the `score` variable, thus ignoring the `(0.1579 * difficult_words)` bit. You can test this by simply putting those three lines all onto one then seeing the spec tests fail.

```
  1) TextStat When testing the TextStat class returns the correct Dale–Chall readability score
     Failure/Error: expect(score).to be 4.79
     
       expected #<Float:43144484430209354> => 4.79
            got #<Float:65302194596872194> => 7.25
```

In terms of a fix, suggest either move them onto one line, or move the `+` operator to the end of the previous line as the parser would then read it as expected..

FYI I have raised an issue with Ruby maintainers to see what the deal is with the parser issue! See https://bugs.ruby-lang.org/issues/16520

### PR DESCRIPTION
**Pull request by abrom**
Fixes #31 

Fix calculation bug in Dale/Chall readability score
Remove unnecessary `max` from syllable count
Remove unnecessary cast from avg_sentence_length
Remove unnecessary cast from avg_syllables_per_word
Remove unnecessary cast from avg_letter_per_word
Remove unnecessary cast from avg_sentence_per_word
Remove unnecessary cast from flesch_reading_ease
Remove unnecessary cast from flesch_kincaid_grade
Improved readability of smog_index
Remove unnecessary cast and fixed scaler typo in coleman_liau_index
Improved readability and unnecessary rounding from automated_readability_index
Improved readability of linsear_write_formula
Improved readability of difficult_words
Improved readability of gunning_fog
Improved readability of lix

### CODE REVIEW

File: lib/textstat.rb [hunk 1]
```diff
@@ -23,7 +23,7 @@ def self.syllable_count(text, language = 'en_us')
     count = 0
     text.split(' ').each do |word|
       word_hyphenated = dictionary.visualise(word)
-      count += [1, word_hyphenated.count('-') + 1].max
```
Comment (abrom) [inline lib/textstat.rb]: Not sure what the original intent was here. `count` will always return >= 0 and adding one will always be >= 1 so the `max` of that and one will always be >= 1?!

File: lib/textstat.rb [hunk 2]
```diff
@@ -33,7 +33,7 @@ def self.sentence_count(text)
   end
 
   def self.avg_sentence_length(text)
-    asl = lexicon_count(text).to_f / sentence_count(text).to_f
+    asl = lexicon_count(text).to_f / sentence_count(text)
```
Comment (abrom) [inline lib/textstat.rb]: Casting on both sides isn't necessary. Ruby will do that for us

File: lib/textstat.rb [hunk 3]
```diff
@@ -67,16 +67,14 @@ def self.avg_sentence_per_word(text)
   def self.flesch_reading_ease(text)
     sentence_length    = avg_sentence_length(text)
     syllables_per_word = avg_syllables_per_word(text)
-    flesch = (
-    206.835 - (1.015 * sentence_length).to_f - (84.6 * syllables_per_word).to_f
-    )
+    flesch = 206.835 - 1.015 * sentence_length - 84.6 * syllables_per_word
```
Comment (abrom) [inline lib/textstat.rb]: operator precedence means that the brackets weren't needed, and `<float> * <integer>` will be a float so no need to cast it again

File: lib/textstat.rb [hunk 4]
```diff
@@ -95,37 +93,35 @@ def self.smog_index(text)
     if sentences >= 3
       begin
         polysyllab = polysyllab_count(text)
-        smog = (
-        (1.043 * (30 * (polysyllab / sentences))**0.5) + 3.1291)
-        return smog.round(1)
+        smog = 1.043 * Math.sqrt(30.0 * polysyllab / sentences) + 3.1291
```
Comment (abrom) [inline lib/textstat.rb]: `**0.5` and `Math.sqrt` are functionally the same so suggest erring on the side of readability here

File: lib/textstat.rb [hunk 5]
```diff
@@ -95,37 +93,35 @@ def self.smog_index(text)
...
+      0.0
     end
   end
 
   def self.coleman_liau_index(text)
-    letters   = (avg_letter_per_word(text) * 100).round(2)
+    letters = (avg_letter_per_word(text) * 100).round(2)
     sentences = (avg_sentence_per_word(text) * 100).round(2)
-    coleman   = ((0.058 * letters) - (0.296 * sentences) - 15.8).to_f
+    coleman = 0.0588 * letters - 0.296 * sentences - 15.8
```
Comment (abrom) [inline lib/textstat.rb]: I believe `0.0588` is the correct scaler here

File: lib/textstat.rb [hunk 6]
```diff
@@ -161,58 +155,49 @@ def self.difficult_words(text, language = 'en_us')
...
     diff_words_set = Set.new
     text_list.each do |value|
-      unless easy_words.include? value
-        if syllable_count(value) > 1
-          diff_words_set.add(value)
-        end
-      end
+      next if easy_words.include? value
+
+      diff_words_set.add(value) if syllable_count(value) > 1
```
Comment (abrom) [inline lib/textstat.rb]: functionally no change, just less nested if/unless for the win!

File: lib/textstat.rb [hunk 7]
```diff
@@ -161,58 +155,49 @@ def self.difficult_words(text, language = 'en_us')
...
+      per = 100.0 * count / word_count
     rescue ZeroDivisionError
       return 0.0
     end
 
     difficult_words = 100 - per
-    score = (
-    (0.1579 * difficult_words)
-    + (0.0496 * avg_sentence_length(text)))
+    score = 0.1579 * difficult_words + 0.0496 * avg_sentence_length(text)
```
Comment (abrom) [inline lib/textstat.rb]: this was the main issue in terms of calculation bugs per #31

File: lib/textstat.rb [hunk 8]
```diff
@@ -161,58 +155,49 @@ def self.difficult_words(text, language = 'en_us')
...
-    end
-    return score.round(2)
+    score.round(2)
   end
 
   def self.gunning_fog(text)
-    begin
-      per_diff_words = (
-      (difficult_words(text) / lexicon_count(text) * 100) + 5)
+    per_diff_words = 100.0 * difficult_words(text) / lexicon_count(text) + 5
```
Comment (abrom) [inline lib/textstat.rb]: can you explain where the `+ 5` at the end comes from? From what I've read about Gunning Fog it should just be `100.0 * difficult_words(text) / lexicon_count(text)`

File: lib/textstat.rb [hunk 9]
```diff
@@ -95,37 +93,35 @@ def self.smog_index(text)
...
+    words = lexicon_count(text)
     sentences = sentence_count(text)
     begin
-      a = chars.to_f / words.to_f
-      b = words.to_f / sentences.to_f
+      a = chars.to_f / words
+      b = words.to_f / sentences
 
-      readability = (
-      (4.71 * a.round(2) + (0.5 * b.round(2))) - 21.43)
```
Comment (abrom) [inline lib/textstat.rb]: not sure why these were being rounded mid-calculation? I couldn't find any material suggesting that this was a part of the calculation?!

File: lib/textstat.rb (hunk 8 above)
Comment (abrom) [reply lib/textstat.rb]: Also, you'll note I put the `100.0` at the start, thus resulting in the difficult_words / lexicon_count being floating point math (and as a result a significant change in the spec test. Per below, I couldn't find anything to suggest that this should have been integer math???
